# Basic
title: The Warrior King
subtitle: 懦夫屡败，勇者无敌
welcome_message: <a href="http://jinchuang.me" target="_blank">个人域名：jinchuang.me</a>
description: 你好，我是金闯，一个和编程打交道的手艺人。
creator: <a href="http://jinchuang.me">WarriorKing</a>

url: "http://jinchuang.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'http://jinchuang.me/project'}
    - {title: 资源收集, description: 资源收集, url: 'http://jinchuang.me/resources'}
    - {title: 订阅, description: 邮件订阅本站, url: 'http://jinchuang.me/feed.xml'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: WarriorKing
    duoshuo: warriorking

# Social
social:
    weibo: 大猩猩在思考
    github: jinchuang
    twitter: WarriorKing1987
    mail: 45545338@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
